In [4]:
import numpy as np
arr = np.array([1, 2, 3])
list = arr.tolist()
print(list)

[1, 2, 3]


In [24]:
import numpy as np
arr1 =np.array([[0,1,2],[3,4,5],[6,7,8]], dtype=np.float64)
diag = arr1.trace()
print(diag)

12.0


In [61]:
import numpy as np
arr2 = np.array([[2,3,4],[5,6,7]])
x = 3
list2 = arr2.tolist()
for num in list2:
    for j in num:
        if j>x:
            print(j)


4
5
6
7


In [66]:
import numpy as np
first = np.array([[1,1],[1,1]])
second = np.array([[2,2],[2,2]])
c =np.sum([first, second], axis=0)
print(c)

[[3 3]
 [3 3]]


In [72]:
a= np.random.randint(3,6,size=(2,4))
for i in a:
    print(i)
    b=i.mean()
    print(b)
    for j in i:
        c=j-b
    print(c)

[3 4 3 4]
3.5
0.5
[4 4 4 3]
3.75
-0.75
